### PR TITLE
Fix username config getting and add error handling

### PR DESCRIPTION
**Pull request by jdloft**
Not sure if this is still being maintained but I'm going to try and start using this instead of `git-review`. These are some modifications that made it work for me. I saw some lines that seemed to duplicate the same kind of functionality but in the wrong places. I also decided to fix the version badge on the README.

### CODE REVIEW

**Comment by legoktm** [comment]
It's maintained in the sense that I use it daily and it still works :)

**Comment by jdloft** [comment]
Changed the error messages to be more generic and `sys.exit` with them.

**Comment by legoktm** [comment]
Sorry about letting this sit for a full year, I'll take a look at this over the next few days.

**Comment by legoktm** [comment]
And, it took another year :( but I manually re-applied and merged in all of your changes. Thanks!

**Pull request closed without merging**
